name: Playground Server Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "playground/server/**"
      - .github/workflows/playground-server-test.yml

concurrency:
  # ref for branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        id: setup-python
        with:
          python-version-file: "./playground/server/pyproject.toml"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies with uv
        run: |
          uv sync
        working-directory: playground/server
      - name: Run lint with uv
        run: |
          uv run ruff check .
          uv run ruff format --check .
        working-directory: playground/server

  server-test:
    name: Server Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        id: setup-python
        with:
          python-version-file: "./playground/server/pyproject.toml"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies with uv
        run: |
          uv sync
        working-directory: playground/server
      - name: Run tests for API
        run: |
          uv run pytest
        working-directory: playground/server
